name: CI and Deploy Coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          pytest --cov=src --cov-report=html --cov-report=xml

      - name: Debug htmlcov directory
        run: |
          echo "Listing contents of htmlcov directory before deployment:"
          ls -R htmlcov

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: htmlcov

      - name: Debug gh-pages branch after deployment
        run: |
          echo "Cloning gh-pages branch to verify deployment:"
          git clone --branch gh-pages https://github.com/${{ github.repository }}.git gh-pages-branch
          echo "Listing contents of gh-pages branch:"
          ls -R gh-pages-branch
