name: "CI/CD Pipeline"

on:
  workflow_run:
    workflows: ["Security Analysis"]  # Renamed from CodeQL for clarity
    types:
      - completed
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write
  pages: write
  security-events: write
  actions: read
  checks: read

env:
  PYTHON_VERSION: '3.x'
  COVERAGE_REPORT_DIR: htmlcov
  MIN_COVERAGE: 30  # Minimum required coverage percentage

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    outputs:
      coverage: ${{ steps.get-coverage.outputs.coverage }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha || github.ref }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          pytest --cov=src --cov-report=html --cov-report=json

      - name: Get coverage percentage
        id: get-coverage
        run: |
          COVERAGE=$(jq -r '.totals.percent_covered' coverage.json | xargs printf "%.0f")
          echo "coverage=$COVERAGE" >> "$GITHUB_OUTPUT"
          echo "Coverage: $COVERAGE%"

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coverage.json
            ${{ env.COVERAGE_REPORT_DIR }}
          retention-days: 1

  quality-gate:
    needs: test
    if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Check coverage threshold
        run: |
          COVERAGE=${{ needs.test.outputs.coverage }}
          if (( $(echo "$COVERAGE < ${{ env.MIN_COVERAGE }}" | bc -l) )); then
            echo "Coverage ${COVERAGE}% is below minimum threshold of ${{ env.MIN_COVERAGE }}%"
            exit 1
          fi
          echo "Coverage ${COVERAGE}% meets minimum threshold of ${{ env.MIN_COVERAGE }}%"

  deploy:
    needs: [test, quality-gate]
    if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.WORKFLOW_TOKEN }}
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          name: coverage-report

      - name: Update coverage badge
        run: |
          COVERAGE=$(jq -r '.totals.percent_covered' coverage.json | xargs printf "%.0f")
          echo "Coverage: $COVERAGE%"
          sed -i "s/coverage-[0-9.]*%25/coverage-${COVERAGE}%25/" README.md
          
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          if git diff --quiet README.md; then
            echo "No changes to README.md, skipping commit"
          else
            git add README.md
            git commit -m "Update coverage badge to ${COVERAGE}%"
            git push origin HEAD:main || {
              echo "Failed to push to main branch"
              exit 1
            }
          fi

      - name: Deploy to GitHub Pages
        run: |
          git checkout --orphan gh-pages
          find . -maxdepth 1 -not -name "${COVERAGE_REPORT_DIR}" -not -name '.git' -not -name '.gitignore' -exec rm -rf {} \;
          cp -r ${COVERAGE_REPORT_DIR}/* .
          touch .nojekyll
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Deploy coverage report for commit ${GITHUB_SHA}"
          git push --force origin gh-pages
