name: Deploy Coverage Report

on:
  workflow_call:
    inputs:
      coverage-artifact:
        required: true
        type: string
    secrets:
      deploy_token:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.coverage-artifact }}
          path: coverage-report

      - name: Check coverage report
        run: |
          if [ ! -d "coverage-report/htmlcov" ]; then
            echo "Error: Coverage report not found in expected location"
            exit 1
          fi

      - name: Generate coverage badge
        run: |
          if [ -f "coverage-report/coverage.xml" ]; then
            COVERAGE=$(python3 -c "import xml.etree.ElementTree as ET; tree = ET.parse('coverage-report/coverage.xml'); root = tree.getroot(); print(root.attrib['line-rate'])")
            echo "coverage: $COVERAGE"
            echo "![Coverage](https://img.shields.io/badge/coverage-${COVERAGE}%25-brightgreen.svg)" > coverage-report/badge.md
          else
            echo "coverage.xml not found, using default badge"
            echo "![Coverage](https://img.shields.io/badge/coverage-0%25-red.svg)" > coverage-report/badge.md
          fi

      - name: Create index.html
        run: |
          echo "<!DOCTYPE html>
          <html>
          <head>
            <title>Task Manager Coverage Report</title>
            <meta http-equiv='refresh' content='0;url=htmlcov/index.html'>
          </head>
          <body>
            <p>Redirecting to coverage report...</p>
          </body>
          </html>" > coverage-report/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.deploy_token }}
          publish_dir: ./coverage-report
          destination_dir: .
          force_orphan: true

      - name: Verify deployment
        run: |
          echo "Waiting for GitHub Pages to update..."
          sleep 10
          curl -I https://ryancowan.github.io/python-poc/ 