name: CI and Deploy Coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          pytest --cov=src --cov-report=html --cov-report=xml

      - name: Debug htmlcov directory
        run: |
          echo "Listing contents of htmlcov directory:" && ls -la htmlcov

      - name: Debug GitHub Pages branch before deployment
        run: |
          echo "Fetching and listing contents of gh-pages branch before deployment:" && \
          git fetch origin gh-pages && \
          git checkout gh-pages && \
          ls -la

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: htmlcov

      - name: Debug GitHub Pages branch after deployment
        run: |
          echo "Fetching and listing contents of gh-pages branch after deployment:" && \
          git fetch origin gh-pages && \
          git checkout gh-pages && \
          ls -la
