name: CI and Deploy Coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    if: github.event.commits[0].author.email != 'actions@github.com'  # Prevent recursion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for proper git history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: pytest --cov=src --cov-report=html --cov-report=xml

      - name: Update Coverage Badge in README (main branch)
        if: github.ref == 'refs/heads/main'
        run: |
          COVERAGE=$(grep -oP 'line-rate="\K[0-9.]+' coverage.xml | awk '{printf("%d", $1 * 100)}')
          if [ -z "$COVERAGE" ] || [ "$COVERAGE" -lt 0 ] || [ "$COVERAGE" -gt 100 ]; then
            echo "Error: Invalid coverage percentage. Exiting."
            exit 1
          fi
          BADGE_URL="https://img.shields.io/badge/coverage-${COVERAGE}%25-brightgreen.svg"
          sed -i 's|\[!\[Coverage\]([^)]*)\]([^)]*)|\[!\[Coverage\]('"${BADGE_URL}"')\](https://rynpc.github.io/python-poc/)|' README.md
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update coverage badge to ${COVERAGE}%" || echo "No changes to commit."
          git push origin HEAD:main

      - name: Deploy Coverage Report to GitHub Pages
        if: github.ref == 'refs/heads/main'
        run: |
          git checkout --orphan gh-pages
          cp -r htmlcov/* .
          touch .nojekyll
          git add -A
          git commit -m "Deploy coverage report" || echo "No changes to commit"
          git push --force origin gh-pages
