name: CI and Deploy Coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    if: github.event.commits[0].author.email != 'actions@github.com'  # Prevent recursion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for proper git history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: pytest --cov=src --cov-report=html --cov-report=xml

      - name: Update Coverage Badge in README (main branch)
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Updating coverage badge..."
          COVERAGE=$(python -m src.coverage_utils.get_coverage --coverage-xml coverage.xml --readme README.md)
          if [ $? -ne 0 ]; then
            echo "Error updating coverage badge"
            exit 1
          fi
          echo "Coverage: $COVERAGE%"
          
          # Commit and push changes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update coverage badge to ${COVERAGE}%" || echo "No changes to commit"
          git push origin HEAD:main || exit 1

      - name: Deploy Coverage Report to GitHub Pages
        if: github.ref == 'refs/heads/main'
        run: |
          git checkout --orphan gh-pages
          cp -r htmlcov/* .
          touch .nojekyll
          git add -A
          git commit -m "Deploy coverage report" || echo "No changes to commit"
          git push --force origin gh-pages
